spring:
  application:
    name: cloud-stream-binding-kafka-app
  cloud:
    stream:
      kafka:
        binder:
          brokers: 0.0.0.0:8080
          configuration:
            auto-offset-reset: latest
      bindings:
        customChannel:                   #Channel name
          destination: name-of-topic     #Destination to which the message is sent (topic)
          group: input-group-N
          contentType: application/json
          consumer:
            max-attempts: 1
            autoCommitOffset: true
            autoCommitOnError: false